### ISSUE TITLE
[RX671-RSK][GCC][Demos] Bootloader & OTA demo

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#11]
# Branch
- feat_rx_development_202012.00_bsp_wifi_20210512

# Environment
- e2studio 2021-07 R20210511-1434
- GCC v8.3.0.202004
- RDP_v131a
- WiFi_0528
- MOT Converter tool 20210603 [sent by SP]: Clone [here](https://github.com/gnomons-sw/renesas-mot-file-converter)
- RFP version v3.08.02 [sent by SP]: The readme file says “RX65x” should be selected if you use RX671. Clone [here](https://github.com/gnomons-sw/renesas-flash-programmer)
- IDT v4.0.3 with test suite FRQ_1.5.0

# Baseline
- RX671-RSK CCRX: To change compiler

# Deliverables
- [x] bootloader.c / bootloader.h 
- [x] TeraTerm log: OTA

**Comment by vinhloi** [comment]
Finish MQTT demo
