### ISSUE TITLE
RX65N-CK GCC: Verify the bootloader works with MOT file converter tag1.01

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#15]
Update the bootloader to work with MOT file converter tag 1.01.

# Branch
- feat_rx_development_202012.00_bsp_wifi_20210512

# Environment
- e2studio 2021-04
- GCC v8.3.0.202004
- RDP_v125 (i.e. BSP_v552)
- WiFi_0528
- MOT Converter tool tag 1.0.1

# Reference
- RX65N-CK fix_GCC [#fb495b7](https://github.com/renesas/amazon-freertos/commit/fb495b74720b9c314c1c7ec3b28c3e5df4994662)

# Deliverables
- [x] RDP_v125: Update to WiFi_0528
- [x] Source code: aws_demos (GitHub)
- [x] Source code: bootloader (GitHub)
- [x] TeraTerm demo log (OTA)

**Comment by vinhloi** [comment]
done
