### ISSUE TITLE
RX65N-CK GCC aws_demos: Multi boards appear in the e2s Project Explorer

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#16]
In the `aws_demos` project, `rx65n-cloud-kit-uart-sx-ulpgn` and `rx65n-cloud-kit-uart-sx-ulpgn-gcc` both appear in the `vendors/renesas/boards` folder in the Project Explorer.

Expected: Only `rx65n-cloud-kit-uart-sx-ulpgn-gcc` appears.

**Comment by vinhloi** [comment]
fixed
