### ISSUE TITLE
RX671-RSK MQTT CCRX demo doesn't work

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#2]

**Comment by Wolveries** [comment]
[Phenomena]
  From terminal log:
   - TLS_Connect() fails.
   - Connection to the broker failed
   - Error running demo
  
[Cause]
 The size allocated for PKCS_CONTROL_BLOCK is a quarter of data flash as common convention from other boards.
 The data flash of RX671-RSK is 8KB, so PKCS_CONTROL_BLOCK is allocated 2KB (2048 bytes).
 However, this is not enough to store the device certificate and private key (~2051 bytes for the data only).
 This causes data corruption. Then TLS_Connect() cannot use the data for a secure connection.

[How to find]
 Run the demo until xProvisionDevice() in aws_dev_mode_key_provisioning.c.
 This function writes the device certificate and private key (provided in aws_clientcredential_keys.h) to the variable pkcs_control_block_data_image (in RAM) and pkcs_control_block_data (in data flash).
 Before invoking xProvisionCertificate(), the data in pkcs_control_block_data_image is initial value (~0).
 After xProvisionCertificate() is invoked, the metadata of certificate (converted format) is written to the variable at pkcs_control_block_data_image.data.pkcs_data[3]. 
 A quick checking using "Expressions" view shows that the metadata is valid:
  - ulDataSize = 861
  - local_storage_index = 0
  - status = 1 (PKCS_DATA_STATUS_REGISTERED)
 After xProvisionPrivateKey() is invoked, the data in the variable pkcs_control_block_data_image seems to be corrupted. All metadata in pkcs_control_block_data_image.data.pkcs_data are assigned to very big values (at least, "status" cannot be larger than 2).

 Running steps by steps into xProvisionPrivateKey() > prvProvisionPrivateRSAKey() > C_CreateObject() > prvCreatePrivateKey() > prvCreateRsaKey() > prvSaveDerKeyToPal(): In prvSaveDerKeyToPal() the size of private key (converted form) is calculated as 1190 bytes. Then the total size of certificate data (861) and private key data (1190) is larger than 2KB. This causes data corruption.

[How to fix]
 - Increase the size of PKCS_CONTROL_BLOCK (i.e. 'local_storage' in concrete) to 3KB.
 - Re-calculate the hash ('hash_sha256').
