### ISSUE TITLE
[RX671-RSK][CCRX][WiFi v1.11][IDT] Log output is unxepected

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#54]
Troubleshoot why the log output is unexpected.

If `WIFI_CFG_SOCKETS_RECEIVE_BUFFER_SIZE` is greater than 1024*2, then the log output is unexpected.

# Test configuration
```
tcptestECHO_TEST_SYNC_TIMEOUT = 800K
integrationtestportableMAX_NUM_UNSECURE_SOCKETS = 4u
mqttconfigTCP_SEND_TIMEOUT_MS = 20
WIFI_CFG_SOCKETS_RECEIVE_BUFFER_SIZE = 1024*10
ipconfigTCP_TX_BUFFER_LENGTH = 1480*10
ipconfigTCP_RX_BUFFER_LENGTH = 1480*10
WIFI_CFG_CREATABLE_SOCKETS = 5
vTaskDelay in SOCKET_SEND, SOCKET_RECV : //vTaskDelay(1)
```

# Branch
- feat_rx_development_202012.00_bsp_wifi_20210512

# Environment
- e2studio 2021-07 R20210511-1434
- CCRX v3.03
- RDP_v131a
- WiFi_v1.11 [sent by SP] 
- MOT Converter tool [modified by Gnomons]: Clone [here](https://github.com/gnomons-sw/renesas-mot-file-converter)
- RFP version v3.08.02 [sent by SP]: The readme file says “RX65x” should be selected if you use RX671. 
- IDT v4.0.3 with test suite FRQ_1.5.0

# Baseline
- RX671-RSK CCRX [be68c43090044524566aee45822db9089c3dff84]

# Deliverables
- [x] Reproduce the issue: Log files
- [x] Investigation report

**Comment by Wolveries** [comment]
Setting "WIFI_CFG_SOCKETS_RECEIVE_BUFFER_SIZE = 1024*10" makes the B_1 section exceeds the internal RAM limit size. This causes the test cannot be run.

**Comment by tu-thai** [comment]
> 
> 
> Setting "WIFI_CFG_SOCKETS_RECEIVE_BUFFER_SIZE = 1024*10" makes the B_1 section exceeds the internal RAM limit size. This causes the test cannot be run.

~~This causes the test cannot be run.~~
The test ran unexpectedly.  (Program ran away.)
